seo: Add title to all docs pages
flowforge/flowforge pull request #1750
Opened 2023-02-24 10:29 UTC by ZJvandeWeg

2023-03-02 15:59 UTC, joepavitt commented
Similar to the equivalent Handbook PR, ideally this uses `navTitle` or `meta.title` instead as discussed

2023-04-11 17:56 UTC, ZJvandeWeg commented
@joepavitt This should be ready for review and merging.

2023-04-12 08:33 UTC, joepavitt requested changes

2023-04-12 08:33 UTC, joepavitt commented on docs/contribute/workflows/README.md
> +title: State Flows
```suggestion
navTitle: State Flows
```

2023-04-12 08:33 UTC, joepavitt commented on docs/contribute/workflows/signup.md
> +title: User Sign up Flow
```suggestion
navTitle: User Sign up Flow
```

2023-04-12 08:33 UTC, joepavitt commented on docs/contribute/workflows/team-create.md
> +title: Team creation Flow
```suggestion
navTitle: Team creation Flow
```

2023-04-12 08:39 UTC, joepavitt commented
Given the release tomorrow, is there much merit in the backport label?

2023-04-12 08:39 UTC, merged