Personal access tokens
flowforge/flowforge pull request #2584
Opened 2023-08-14 12:33 UTC by hardillb

fixes #14 
## Description

Adds support for creating a Personal Access Token.

Adds a new entry to the User Settings -> Security tab

Allows multiple tokens with different scopes.

## Related Issue(s)

#14

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-08-14 13:30 UTC, hardillb commented
OK, I don't understand the UI Tests failure.

If you get a second @joepavitt can you have a look (and feel free to critique the whole UI, there is a feature demo video in the channel)

2023-08-14 20:59 UTC, joepavitt commented
Just had a little look at the logs. These are all of the ui-components. Have you rebased since we merged?

Can only think that's a cause...

2023-08-15 08:42 UTC, hardillb commented
Rebased and still failing the same way

2023-08-16 09:18 UTC, joepavitt commented
@hardillb noticed the latest tests are all passing? What changed?

2023-08-16 09:21 UTC, hardillb commented
@joepavitt The actual failure was a VS code auto complete thing.

It had injected:

```
<script>
...
export default ({
...
})
</script>
```

Note the extra none curly braces round the export bit

2023-08-16 09:31 UTC, joepavitt commented
so is this "ready for review"?

2023-08-18 08:50 UTC, hardillb commented
I add more tests... and code coverage goes down

2023-08-18 09:14 UTC, joepavitt commented
Have modified the dialog slightly to improve spacing in layout, but also make it more explicit styling on the disabled state & make the checkbox say "Add Expiry Date", rather than "never":

<img width="632" alt="Screenshot 2023-08-18 at 10 13 15" src="https://github.com/flowforge/flowforge/assets/99246719/897c4bf8-501d-4520-8009-3c0d021bf0c2">

<img width="626" alt="Screenshot 2023-08-18 at 10 13 19" src="https://github.com/flowforge/flowforge/assets/99246719/a4774e93-7a54-4931-92e1-4d5c1d26c076">

2023-08-18 09:30 UTC, joepavitt commented
Am also going to add E2E tests

2023-08-18 14:08 UTC, joepavitt approved these changes
Approved front-end, E2E's also added. Leaving server-side eyes to Nick

2023-08-18 15:54 UTC, knolleary requested changes

2023-08-18 15:54 UTC, knolleary commented on forge/db/migrations/20230808-01-add-access-token-name.js
> +/**
This migration will need to be renamed. We have already merged `20230814-01-add-description-to-applications` so this file will need a later date.

2023-08-18 15:54 UTC, knolleary commented on forge/routes/api/settings.js
> +                response['platform:auth:permissions'] = Permissions
Given we aren't including custom scopes for this iteration we don't need to expose the full permissions table.

2023-08-18 15:54 UTC, knolleary commented on frontend/src/pages/account/Security/dialogs/TokenDialog.vue
> +        },
```suggestion
    methods: {
```
As per other comment - not including scopes in this iteration, so suggest removing this code as we may want a different approach in the future.

2023-08-18 15:54 UTC, knolleary commented on frontend/src/pages/account/components/ExpiryCell.vue
> +    props: ['expiresAt'],
Linting warning:

`Prop "expiresAt" should define at least its type`

2023-08-18 15:54 UTC, knolleary commented on forge/routes/api/user.js
> +    app.get('/pat', {
Sorry to say, I think the api end point should be `/api/v1/user/tokens`...

2023-08-22 15:05 UTC, knolleary commented on frontend/src/pages/account/Security/dialogs/TokenDialog.vue
> +    <ff-dialog ref="dialog" data-el="add-token-dialog" header="Add Token" :confirm-label="token ? 'Save' : 'Create'" :disablePrimary="disableConfirm" @confirm="confirm()">
```suggestion
    <ff-dialog ref="dialog" data-el="add-token-dialog" :header="(token ? 'Edit' : 'Add') + ' Token'" :confirm-label="token ? 'Save' : 'Create'" :disablePrimary="disableConfirm" @confirm="confirm()">
```

Update title to reflect add/edit mode

2023-08-22 15:06 UTC, knolleary commented on frontend/src/pages/account/Security/dialogs/TokenDialog.vue
> +                    <template #description>Token name</template>
```suggestion
                <FormRow v-model="input.name" data-form="token-name" :disabled="edit">
                    Token name
```

Feels redundant to have both the label and description set to much the same - suggest collapsing down to just the label.

2023-08-22 15:29 UTC, hardillb commented
argh, I assume removing the "Name" label has broken the cypress tests

2023-08-22 15:31 UTC, knolleary commented
@hardillb I eyeballed it and didn't spot a reason for that change to require a UI test change... but I'll dig in.

2023-08-22 15:36 UTC, knolleary commented
@hardillb Don't think this is a related failure. The tests pass locally; unless I run them repeatedly then sometimes they fail.

2023-08-22 15:52 UTC, knolleary commented
Got it - the tests use the count of selectable table rows as a proxy for how many tokens there are. By making them not selectable, it isn't finding them.

The fiddly bit is the 'No data found' row needs to be accounted for.... working on it

2023-08-22 15:58 UTC, knolleary commented
@joepavitt I'm modifying it to be more consistent with the Device Provisioning Tokens table we already have:

When there are no tokens, rather than show the default 'no data found' message, it has a custom element:

<img width="939" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/e4d23a74-b2a9-4fbe-a519-9bde33eafc00">

2023-08-22 16:09 UTC, knolleary commented
Have pushed an update so the token table now has a consistent appearance with the provisioning token table:

<img width="933" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/f94396e6-7a8e-4f02-a9bd-cb9443e11ecb">

 - Added SectionHeader with help text
 - Changed button to `+ Add Token`
 - Changed the 'empty state' to be a custom message - which then also makes the tests easier to handle the empty state (no longer needing to check for `selectable`)

2023-08-22 16:31 UTC, merged