Add backend support for device owned snapshots
flowforge/flowforge pull request #2738
Opened 2023-09-13 07:22 UTC by Steve-Mcl

## Description

Backend work as part of implementing #2609.

* Migration to add column `DeviceId` to `ProjectSnapshots` table
   * This field signifies a snapshot of a device owned by an application
* Adds virtual column `ownerType` to the `ProjectSnapshots` model 
   * The value of this field will be `instance` or `device`. `null` signifies snapshot is orphaned
* Adds controller `DeviceSnapshot` with function `createSnapshotFromDevice` for gathering a snapshot from an application owned device.  This mirrors the `ProjectSnapshot`
* Adds view `DeviceSnapshot` which mirrors `ProjectSnapshot`
* Adds Routes/API `deviceSnapshots` which mirrors `projectSnapshots`

### API info
* `deviceSnapshots` is mounted off the `device` routes. This is the same as how `projectSnapshots` is mounted off `project`
* The APIs for `deviceSnapshots` mirror the APIs in  `projectSnapshots` but differ by arguments (and process/scope)
  * GET '/' (`/api/v1/devices/:deviceId/snapshots/`) - Get list of all snapshots for a device
  * GET '/' (`/api/v1/devices/:deviceId/snapshots/:snapshotId`) - Get details of a snapshot - metadata only
  * DELETE '/' (`/api/v1/devices/:deviceId/snapshots/:snapshotId`) - Delete a snapshot
  * POST '/' (`/api/v1/devices/:deviceId/snapshots/`) - Create a snapshot

### Tests
```
  Device Snapshots API
    Create device snapshot
      ✔ Non-owner can create device snapshot
      ✔ Non-member cannot create project snapshot
      ✔ Create a device snapshot - empty state
      ✔ Create a device snapshot - capture real state
    Get snapshot information
      ✔ Non-member cannot get device snapshot
      ✔ Get snapshot
    Delete a snapshot
      ✔ Non-owner cannot delete a device snapshot
      ✔ Team owner can delete a project snapshot

 DeviceSnapshot controller
    createSnapshot
      ✔ creates a snapshot of a device owned by an application
```

### NOTES:
* Existing route `/api/v1/devices/:deviceId/snapshot` for getting an instance bound snapshot from a device still remains. We may wish to consider moving, or renaming this route due to being unclear/easily mistakable with `/api/v1/devices/:deviceId/snapshots` 

## Related Issue(s)

#2609 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-09-13 08:07 UTC, Steve-Mcl commented
backend PG test failure makes no sense:

```
  1) User API
       User deletes own account
         Last owner of a team cannot delete own account:
     AssertionError: expected Object {
  code: 'unexpected_error',
  error: 'TypeError: Cannot read properties of null (reading \'id\')'
} to have property error of 'Error: Cannot delete the last owner of a team' (got 'TypeError: Cannot read properties of null (reading \'id\')')
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as property] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/unit/forge/routes/api/user_spec.js:626:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Not sure why this completely unrelated code is erroring to start with never mind the fact what it state. e.g. the code at 
at `test/unit/forge/routes/api/user_spec.js:626:30` makes no reference to an `id` at all!

2023-09-13 10:05 UTC, Steve-Mcl commented
PG test fail is not making sense. Full discussion [here](https://flowforgeworkspace.slack.com/archives/C032Q63FGG1/p1694594946327359)

I short, local execution of PG tests pass!
![image](https://github.com/flowforge/flowforge/assets/44235289/a223886e-0691-442a-b954-6c726474eaf6)

2023-09-13 10:57 UTC, knolleary requested changes
A quick first pass through. I'm not sure about adding `DeviceSnapshot` controllers and views as we have so far maintained a 1:1 relationship between controllers/views and Models.

I do think the view should be reusing the existing Snapshot views we have - I can't at a glance see anything different between them, and if necessary we can augment the existing views with optional fields rather than create a whole copy.

2023-09-13 10:57 UTC, knolleary commented on forge/db/views/DeviceSnapshot.js
Unless I'm failing to see it, this looks identical to the existing Snapshot views. We should only have one definition of what a Snapshot looks like on the API. Please reuse the views we already have.

2023-09-13 11:25 UTC, Steve-Mcl commented on forge/db/views/DeviceSnapshot.js
As I'm certain you realise, I did this for code clarity. Happy to rework as proposed.

2023-09-13 11:27 UTC, Steve-Mcl commented on forge/db/controllers/DeviceSnapshot.js
Will rework it into ProjectSnapshot. Though it will decrease clarity in the code until a future point when we work out the wrinkles or something drives this in another direction.

2023-09-13 13:11 UTC, Steve-Mcl commented on forge/db/views/DeviceSnapshot.js
resolved in [1b6055f](https://github.com/flowforge/flowforge/pull/2738/commits/1b6055f7660e305d6a98308d965579ad31eb3357)

2023-09-13 15:03 UTC, Steve-Mcl commented
After some discussion with @joepavitt I am adding one more API - for getting all snapshots by Application.

Will switch this PR to draft until that is added.

FYI: This will be necessary to permit a singular view of instance and device snapshots as described in figma

2023-09-13 19:33 UTC, Steve-Mcl commented
Added all application snapshot access via `/api/v1/applications/:id/snapshots` as discussed with @joepavitt 

Switching PR back to ready for review.

2023-09-18 11:58 UTC, knolleary approved these changes
Looks good from a high level review.

2023-09-25 17:33 UTC, Steve-Mcl commented
@knolleary the actionable TODOs we discussed last week are mostly covered in #1978 

Remaining TODOs are for when we have device settings/grouping/tagging

2023-09-26 15:22 UTC, knolleary commented
Approved - @Steve-Mcl will let you merge in coordination with #2750 as needed

2023-09-27 08:35 UTC, merged