Add export and project duplication
flowforge/flowforge pull request #528
Opened 2022-05-03 09:55 UTC by hardillb

Contains a Vue component for selecting which parts of a Project should be exported. This will be reused for Project duplicate workflow.

Work in progress towards https://github.com/flowforge/flowforge/issues/270 and #271

2022-05-05 10:47 UTC, hardillb commented
@joepavitt can you review the vue in this please. I'm sure it's ugly as hell but it does work...

2022-05-05 10:48 UTC, hardillb commented
I'm starting to think I should disable the export (to JSON blob as that is covered in a different story not in the 0.5 release plan and there is nothing you can do with it yet)

2022-05-05 10:53 UTC, joepavitt requested changes
I will likely modify a few of the dialogs shortly, once I proceed with the update to `forge-ui-components` dialog boxes across the platform.

Mostly looking good, but a lot of commented code and console logs that need clearing.

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/Danger.vue
> +            console.log('copy project', parts)
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/Danger.vue
> +                console.log(result)
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/Danger.vue
> +                console.log(result.id)
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/Danger.vue
> +                console.log(result.name)
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/Danger.vue
> +            console.log('Ben')
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/Danger.vue
> +            console.log(parts)
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/dialogs/ExportToProjectDialog.vue
> +<!--
Remove commented out code

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/Settings/dialogs/ExportToProjectDialog.vue
> +                        console.log(projectList.projects[i].id, projectList.projects[i].name)
```suggestion
```

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/components/ExportProjectComponents.vue
> +        <!-- <FormRow type="checkbox" v-model="parts.settings">Settings</FormRow> -->
Remove commented out code

2022-05-05 10:53 UTC, joepavitt commented on frontend/src/pages/project/components/ExportProjectComponents.vue
> +            <!-- <template v-slot:description>Keys only</template> -->
Remove commented out code

2022-05-05 13:02 UTC, joepavitt approved these changes

2022-05-05 15:08 UTC, hardillb commented
Still trying to work out how to clean up the overflow here:

![Screenshot from 2022-05-05 16-06-21](https://user-images.githubusercontent.com/1800845/166953898-71296610-465c-457b-8b91-f7c8b0cde89a.png)

And how to line up:

![Screenshot from 2022-05-05 15-41-06](https://user-images.githubusercontent.com/1800845/166954214-4e68e1a7-652a-4b27-85f6-9bb264f9e7ca.png)

2022-05-05 15:19 UTC, joepavitt commented
> Still trying to work out how to clean up the overflow here

This is an issue with the existing FormRow. I'm honestly okay with pushing as is, with the knowledge that this will be cleaned by as part of the [Dialog Box rework](https://github.com/flowforge/flowforge/issues/520) I'm due to do in 0.5

2022-05-06 08:54 UTC, knolleary commented
#273 (export to zip) is not in plan for 0.5. We haven't done any design work around how the zip is structured. Given this PR implements something, can we get a description of what the zip contents is?

2022-05-06 09:04 UTC, hardillb commented
The JSON output is as follows:

```json
{
   "flows": [],
   "credentials": { "$": "b5db5a7f0aca0467b928136ff4c01e0flfGwBx7CcOrJHef+xp5StVrny+QwoLhn48aLck+gtIGXp012ujlkmNaTW2vJ0I8gyiAY06iZpbDb" },
  "envVars": {
    "FOO": "BAR",
    "TESTING": "ONE"
  },
  "nodes": {
    "node-red": {...},
    "node-red-node-base64": { ... }
  }
}
```

Where `flows` is the array of tabs/nodes and the `nodes` is the nodes section from the settings object. This was a bare minimum I thought we needed. Open to adding something about stacks and templates, but would need to decide what from each.

2022-05-06 09:18 UTC, hardillb commented
We can always remove the UI component for the export to JSON option if needed which will hide this option until we can iterate on it.

2022-05-06 09:20 UTC, knolleary commented
I would prefer we didn't expose this option today.

It will come in useful under the covers for the Device work - but that will also help us validate the format and the contents.

2022-05-06 09:27 UTC, knolleary commented
I find the reworked UI (buttons above text) to be top heavy and imbalanced. I think the buttons are too big.

I would prefer to get back to the original intent of having the button in a right-hand column - but know full well why that's a little awkward without a bigger refactor of FormRow.

@joepavitt would setting `size="small"` be inoffensive?

2022-05-06 09:35 UTC, joepavitt commented
> @joepavitt would setting `size="small"` be inoffensive?

No objection at all from me

2022-05-06 09:45 UTC, knolleary reviewed
Some suggested tweaks to the labels/descriptions

2022-05-06 09:45 UTC, knolleary commented on frontend/src/pages/project/Settings/Danger.vue
> +                project's current state to create a new project.</div>
```suggestion
            <div class="max-w-sm pt-2 pl-5">Create a copy of this project.</div>
```

2022-05-06 09:45 UTC, knolleary commented on frontend/src/pages/project/Settings/Danger.vue
> +            <div class="max-w-sm pt-2 pl-5">Copy a project's state to another existing project.</div>
```suggestion
                <ff-button kind="secondary" @click="showExportToProjectDialog()">Copy to existing project</ff-button>
                <ExportToProjectDialog @exportToProject="exportToProject" ref="exportToProjectDialog"/>
            </div>
            <div class="max-w-sm pt-2 pl-5">Copy the project's state to an existing project.</div>
```

2022-05-06 12:57 UTC, knolleary commented
Just tried the 'Duplicate project' - kept all the default options - and got this error in the runtime:
```
 req: {
      "method": "POST",
      "url": "/api/v1/projects",
      "hostname": "localhost:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 55949
    }
    res: {
      "statusCode": 500
    }
    reqId: "req-s"
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'flow')",
      "stack":
          TypeError: Cannot read properties of null (reading 'flow')
              at Object.<anonymous> (/Users/nol/code/flowforge/flowforge/forge/routes/api/project.js:208:39)
    }
```

Note - this is a NR Project that doesn't actually have any flows as I'm using the stub driver.

---

For the Duplicate project UI, I wonder if we'd be better off taking the user to the existing 'create project' page - but with an added 'copy content from...' section - rather than doing this all via a small dialog box.

Having just one view that handles creating projects would remove duplication in UI code. It would also, for example, ensure the 'agree to extra charges' checkbox is there when billing is enabled.

I am happy to tackle that rework if we think its worthwhile.

2022-05-06 13:03 UTC, hardillb commented
OK, I will ladd tests for missing flows/creds/settings to the project endpoints (e.g when using the stub driver, but also for a project that hasn't deployed yet)

No problem with moving to the create view, but how will it handle the choices of what to duplicate? Or will you pull in the new component into the create vue?

2022-05-06 13:14 UTC, knolleary commented
> Or will you pull in the new component into the create vue?

Yes - reduce, reuse, recycle.

2022-05-06 13:25 UTC, hardillb commented
Sounds good, just working out what to with the export to project, if the source project doesn't have the things it should be exporting. Should it just replace the existing with empty values?

2022-05-09 15:04 UTC, closed without merging