Add Function node exteral modules list
flowforge/flowforge pull request #749
Opened 2022-07-01 20:28 UTC by hardillb

Part of #216

2022-07-01 20:30 UTC, hardillb commented
Fixes #216

2022-07-04 15:16 UTC, knolleary requested changes

2022-07-04 15:16 UTC, knolleary commented on frontend/src/pages/admin/Template/sections/Editor.vue
> +                    Prevent Install of External nodes
```suggestion
                    Prevent Install of External modules
```

2022-07-05 10:23 UTC, knolleary approved these changes

2022-07-05 10:23 UTC, merged