Fix docker run command
flowforge/flowforge pull request #840
Opened 2022-08-02 19:47 UTC by hardillb

Swap `-n` for `--name`

2022-08-02 20:01 UTC, Steve-Mcl approved these changes
yes, that does make it clearer Ben.

2022-08-02 22:03 UTC, Steve-Mcl commented
Actually ben, seems there is another issue with the docs.

They say to set the below in `mosquitto.conf `...

```
    auth_opt_http_getuser_uri /api/broker/auth-client
    auth_opt_http_aclcheck_uri /api/broker/auth-acl
```

However after a fair bit of debugging (in the wrong places ;) ) - I have found these should be ...

```
auth_opt_http_getuser_uri /api/comms/auth/client
auth_opt_http_aclcheck_uri /api/comms/auth/acl
```

2022-08-02 22:08 UTC, Steve-Mcl requested changes
Ben, could lines 105, 106 & 143, 144 be changed from 

```
    auth_opt_http_getuser_uri /api/broker/auth-client
    auth_opt_http_aclcheck_uri /api/broker/auth-acl
```

to 

```
    auth_opt_http_getuser_uri /api/comms/auth/client
    auth_opt_http_aclcheck_uri /api/comms/auth/acl
```

2022-08-03 08:24 UTC, hardillb commented
@Steve-Mcl updated

2022-08-03 08:32 UTC, knolleary requested changes
Fixed auth paths

2022-08-03 08:32 UTC, knolleary commented on docs/install/local/README.md
> +    auth_opt_http_aclcheck_uri /api/comms/auth-acl
```suggestion
    auth_opt_http_getuser_uri /api/comms/auth/client
    auth_opt_http_aclcheck_uri /api/comms/auth/acl
```

2022-08-03 08:32 UTC, knolleary commented on docs/install/local/README.md
> +    auth_opt_http_aclcheck_uri /api/comms/auth-acl
```suggestion
    auth_opt_http_getuser_uri /api/comms/auth/client
    auth_opt_http_aclcheck_uri /api/comms/auth/acl
```

2022-08-03 10:21 UTC, Steve-Mcl approved these changes
Thanks Ben

2022-08-03 10:25 UTC, merged